// Code generated by hertz generator.

package Example

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod4Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod5Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod6Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod10Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod11Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod12Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod7Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod8Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod9Mw() []app.HandlerFunc {
	// your code...
	return nil
}
